/**
 * Flattener: turn `styles/light.json` into `dist/styles/color-scheme.css`.
 *
 * The base (dark) values are already emitted by WordPress under `:root` from
 * theme.json, so this stylesheet only carries the light delta scoped to
 * `[data-theme="light"]`. The header toggle sets `data-theme` on <html>, so the
 * active scheme is selected by attribute alone — no extra fetch, no reflow.
 *
 * Token → CSS custom-property naming follows WordPress' Global Styles
 * convention:
 *   palette   slug  -> --wp--preset--color--{slug}
 *   gradient  slug  -> --wp--preset--gradient--{slug}
 *   duotone   slug  -> --wp--preset--duotone--{slug}
 *   custom    path  -> --wp--custom--{path joined by --, camelCase -> kebab}
 *
 * NOTE on duotone: WordPress renders duotone as an SVG filter referenced via
 * `url(#wp-duotone-...)`, so re-coloring duotones per scheme is not achievable
 * through CSS custom properties alone. The duotone declarations below carry the
 * transformed colors for completeness/parity with light.json; functional
 * per-scheme duotone recoloring would require regenerating the SVG filters.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { isExpression } from './derive.mjs';
import { LIGHT_JSON } from './generate.mjs';

const HERE = path.dirname( fileURLToPath( import.meta.url ) );
const ROOT = path.resolve( HERE, '../..' );

export const COLOR_SCHEME_CSS = path.join( ROOT, 'dist/styles/color-scheme.css' );

/** Convert a camelCase custom key to the kebab-case WordPress uses in var names. */
const kebab = ( s ) => s.replace( /([a-z0-9])([A-Z])/g, '$1-$2' ).toLowerCase();

/**
 * Collect `--wp--custom--…` declarations from the custom.color tree, skipping
 * expression values (they inherit their flipped referents automatically).
 *
 * @param {object} node
 * @param {string[]} trail
 * @param {string[]} out
 */
function customDecls( node, trail, out ) {
	for ( const [ key, value ] of Object.entries( node ) ) {
		const next = [ ...trail, kebab( key ) ];

		if ( typeof value === 'object' && value !== null ) {
			customDecls( value, next, out );
		} else if ( ! isExpression( value ) ) {
			out.push( `--wp--custom--${ next.join( '--' ) }: ${ value };` );
		}
	}
}

/**
 * Build the scoped CSS string from a parsed light.json object.
 *
 * @param {object} light
 * @return {string}
 */
export function buildCss( light ) {
	const color = light.settings?.color ?? {};
	const decls = [];

	for ( const { slug, color: value } of color.palette ?? [] ) {
		if ( ! isExpression( value ) ) {
			decls.push( `--wp--preset--color--${ slug }: ${ value };` );
		}
	}

	for ( const { slug, gradient } of color.gradients ?? [] ) {
		decls.push( `--wp--preset--gradient--${ slug }: ${ gradient };` );
	}

	for ( const { slug, colors } of color.duotone ?? [] ) {
		decls.push( `--wp--preset--duotone--${ slug }: ${ colors.join( ', ' ) };` );
	}

	customDecls( light.settings?.custom?.color ?? {}, [ 'color' ], decls );

	const body = decls.map( ( d ) => `\t${ d }` ).join( '\n' );

	return (
		'/* Generated by tools/color-scheme — do not edit by hand. */\n' +
		'/* Source: styles/light.json (derived from theme.json). */\n' +
		`[data-theme="light"] {\n${ body }\n}\n`
	);
}

/**
 * Read light.json and return the flattened CSS string.
 *
 * @return {string}
 */
export function flatten() {
	const light = JSON.parse( fs.readFileSync( LIGHT_JSON, 'utf8' ) );
	return buildCss( light );
}

/**
 * Flatten and write `dist/styles/color-scheme.css`.
 *
 * @return {string} The written content.
 */
export function writeCss() {
	const content = flatten();
	fs.mkdirSync( path.dirname( COLOR_SCHEME_CSS ), { recursive: true } );
	fs.writeFileSync( COLOR_SCHEME_CSS, content );
	return content;
}
