import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated sidebar — builds the docs tree from the `../docs` folder
 * structure. New markdown files appear automatically.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
